# Generated by Django 5.0.3 on 2024-03-24 12:35

import MediRemind_WebApp.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeucodEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_type_enum', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('advanced', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('sensor_blind_duration', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('value2', models.TextField(blank=True, null=True)),
                ('unit2', models.CharField(blank=True, max_length=50, null=True)),
                ('value3', models.TextField(blank=True, null=True)),
                ('unit3', models.CharField(blank=True, max_length=50, null=True)),
                ('direct_event', models.BooleanField(blank=True, null=True)),
                ('sending_delay', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('caregiver_id', models.IntegerField(blank=True, null=True)),
                ('monitor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_location', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_rtc_clock', models.BooleanField(blank=True, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('device_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('measured_power', models.FloatField(blank=True, null=True)),
                ('signal_to_noise_ratio', models.FloatField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('link_quality', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default=MediRemind_WebApp.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='heucod_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('medication_name', models.CharField(max_length=100)),
                ('reminder_time', models.TimeField(default='00:00:00')),
                ('time_window', models.IntegerField(default=0)),
                ('dosage', models.CharField(default='0 mg', max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=MediRemind_WebApp.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MQTTConfiguration',
            fields=[
                ('mqtt_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('broker_address', models.URLField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('connected_rooms', models.ManyToManyField(blank=True, to='MediRemind_WebApp.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zigbee_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PIR', 'Passive Infrared'), ('VIB', 'Vibration'), ('RGB', 'RGB Light'), ('SWITCH', 'Switch')], max_length=6)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='MediRemind_WebApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('alert_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LIGHT', 'Light'), ('SOUND', 'Sound')], max_length=5)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('sound_file', models.FileField(blank=True, upload_to='alerts/sounds/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='MediRemind_WebApp.room')),
            ],
        ),
    ]
