# Generated by Django 5.0.3 on 2024-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='MQTTConfiguration',
            name='mqtt_id',
            field=models.CharField(max_length=100, primary_key=True),
            preserve_default=False,
        ),
    ]
