# Generated by Django 4.2.6 on 2024-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeucodEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_type_enum', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('advanced', models.TextField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField()),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('sensor_blind_duration', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('value2', models.TextField(blank=True, null=True)),
                ('unit2', models.CharField(blank=True, max_length=50, null=True)),
                ('value3', models.TextField(blank=True, null=True)),
                ('unit3', models.CharField(blank=True, max_length=50, null=True)),
                ('direct_event', models.BooleanField(blank=True, null=True)),
                ('sending_delay', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('caregiver_id', models.IntegerField(blank=True, null=True)),
                ('monitor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_location', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_rtc_clock', models.BooleanField(blank=True, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('device_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('measured_power', models.FloatField(blank=True, null=True)),
                ('signal_to_noise_ratio', models.FloatField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('link_quality', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
