# Generated by Django 4.2.6 on 2024-03-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MediRemind_WebApp', '0002_heucodevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='heucodevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heucod_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
