# Generated by Django 5.0.3 on 2024-03-19 16:37

import MediRemind_WebApp.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('medication_name', models.CharField(max_length=100)),
                ('reminder_time', models.TimeField(default='00:00:00')),
                ('time_window', models.IntegerField(default=0)),
                ('dosage', models.CharField(default='0 mg', max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=MediRemind_WebApp.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MQTTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_address', models.URLField()),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LIGHT', 'Light'), ('SOUND', 'Sound')], max_length=5)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('sound_file', models.FileField(blank=True, upload_to='alerts/sounds/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_configurations', to='MediRemind_WebApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PIR', 'Passive Infrared'), ('VIB', 'Vibration')], max_length=3)),
                ('zigbee_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='MediRemind_WebApp.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
