# Generated by Django 5.0.3 on 2024-03-25 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0002_auto_20240325_2011'),
    ]

    operations = [
    ]
