# Generated by Django 5.0.3 on 2024-03-19 16:47

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0003_medicationschedule_mqttconfiguration_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='schedule_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
