# Generated by Django 5.0.3 on 2024-03-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0003_auto_20240325_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='MediRemind_WebApp.room'),
        ),
        migrations.AlterField(
            model_name='mqttconfiguration',
            name='mqtt_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
