# Generated by Django 5.0.4 on 2024-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0004_alter_device_room_alter_mqttconfiguration_mqtt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('PIR_SENSOR', 'Passive Infrared'), ('VIBRATION_SENSOR', 'Vibration'), ('RGB_STRIP', 'RGB Light'), ('SWITCH', 'Switch')], max_length=100),
        ),
    ]
