# Generated by Django 5.0.4 on 2024-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0005_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='blink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='blink_interval',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='blink_times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
