# Generated by Django 5.0.4 on 2024-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0005_alter_device_type'),
    ]

    operations = [
    ]
