# Generated by Django 5.0.4 on 2024-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
