# Generated by Django 5.0.4 on 2024-04-18 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0009_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlinkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blink', models.BooleanField(default=False)),
                ('blink_interval', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('blink_times', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='blink',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='blink_interval',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='blink_times',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='room',
        ),
        migrations.RemoveField(
            model_name='alertconfiguration',
            name='sound_file',
        ),
        migrations.CreateModel(
            name='StateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(default='Yellow', max_length=7)),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('blink_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediRemind_WebApp.blinkconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='active_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_config', to='MediRemind_WebApp.stateconfig'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='alarmed_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarmed_config', to='MediRemind_WebApp.stateconfig'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='med_missed_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_missed_config', to='MediRemind_WebApp.stateconfig'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='med_taken_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_taken_config', to='MediRemind_WebApp.stateconfig'),
        ),
    ]
