# Generated by Django 5.0.4 on 2024-04-25 07:11

import MediRemind_WebApp.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0010_manualinput_stateconfig'),
    ]

    operations = [

    ]
