# Generated by Django 5.0.4 on 2024-05-07 10:12

import MediRemind_WebApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0013_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=MediRemind_WebApp.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
