# Generated by Django 5.0.4 on 2024-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0013_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualinput',
            name='date',
        ),
        migrations.RemoveField(
            model_name='manualinput',
            name='time',
        ),
        migrations.AddField(
            model_name='manualinput',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
