# Generated by Django 5.0.4 on 2024-05-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0014_alarmed'),
        ('MediRemind_WebApp', '0014_remove_manualinput_date_remove_manualinput_time_and_more'),
    ]

    operations = [
    ]
