# Generated by Django 5.0.4 on 2024-05-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediRemind_WebApp', '0015_merge_20240512_2139'),
        ('MediRemind_WebApp', '0016_alter_event_type'),
    ]

    operations = [
    ]
